name: "run-shexli"
author: "Stuart Hayhurst"
description: "Run Shexli against a built GNOME extension"

branding:
  icon: "flag"
  color: "green"

inputs:
  path:
    description: "Path to the extension bundle"
    required: true
  use-latest-shexli:
    description: "Override the pinned version of Shexli with the latest release"
    required: false
    default: "false"
  acceptable-error-threshold:
    description: "Maximum acceptable number of errors before failing the action (-1 to disable)"
    required: false
    default: "0"
  acceptable-warning-threshold:
    description: "Maximum acceptable number of warnings before failing the action (-1 to disable)"
    required: false
    default: "-1"

runs:
  using: "composite"
  steps:
   - id: setup-python
     uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
     with:
       python-version: "3.14"

   - id: install-shexli-latest
     run: pip install shexli
     if: ${{ inputs.use-latest-shexli == 'true' }}
     shell: bash

   - id: install-shexli-pinned
     run: pip install -r ${{ github.action_path }}/requirements.txt
     if: ${{ inputs.use-latest-shexli != 'true' }}
     shell: bash

   - id: run-shexli
     run: python ${{ github.action_path }}/run-shexli.py
     shell: bash
     env:
       EXTENSION_PATH: "${{ inputs.path }}"
       MAX_ERRORS: "${{ inputs.acceptable-error-threshold }}"
       MAX_WARNINGS: "${{ inputs.acceptable-warning-threshold }}"
