name: "run-shexli"
author: "Stuart Hayhurst"
description: "Run Shexli against a built GNOME extension"

branding:
  icon: "flag"
  color: "green"

inputs:
  path:
    description: "Path to the extension bundle"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
   - id: setup-python
     uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
     with:
       python-version: "3.14"

   - id: install-shexli
     run: pip install -r ${{ github.action_path }}/requirements.txt
     shell: bash

   - id: run-shexli
     run: ${{ github.action_path }}/run-shexli.py
     shell: python
     env:
       EXTENSION_PATH: "${{ inputs.path }}"
